# Generated by Django 5.0.2 on 2024-02-29 00:18

import bookstore.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('died', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('year_create', models.IntegerField(verbose_name='Год написания')),
                ('published_by', models.CharField(max_length=50, verbose_name='Издатель')),
                ('year_published', models.IntegerField(default=bookstore.models.current_year, verbose_name='Год издания')),
                ('sheets', models.IntegerField(verbose_name='Кол-во страниц')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author', verbose_name='Автор')),
            ],
        ),
    ]
